### ISSUE TITLE
Send Message feature does not appear to be working

### ISSUE THREAD

**Issue by blynchNDI** [nditech/apollo#419]
While a telerivet webhook is working for receiving and sending responses to messages texted in, the Send Message button does not seem to be working. On the checklist page, sending a message produces an error. On the participant page, the send message button "succeeds" and doesn't produce an error, but the message does not appear in telerivet. Let me know if you need me to help with testing things on the telerivet side.

**Comment by dodumosu** [comment]
@blynchNDI is the instance set up to send messages through Telerivet, that is, is the `MESSAGING_OUTGOING_GATEWAY` setting in place?

**Comment by blynchNDI** [comment]
@dodumosu I don't think so. That's likely the problem - let me figure out how to configure that

**Comment by dodumosu** [comment]
i've sent you an email.

**Comment by blynchNDI** [comment]
Thanks -  I just checked my settings.ini file and I do actually have it configured (I had forgotten it was called MESSAGING_OUTGOING_GATEWAY). The basic syntax minus the tokens is below, which I assume must be working since messages sent in show up in Apollo and generate responses? On the telerivet side, the tab is labeled incoming message - is there a different webhook configuration I need, or a setting I need to change?

messaging gateway configuration is MESSAGING_OUTGOING_GATEWAY={'type': 'telerivet', 'api_key': '_(the api key I'm using)_', 'project_id': '_the telerivet project id_'}



![Screenshot from 2019-07-12 11-33-27](https://user-images.githubusercontent.com/31080607/61140316-4076f480-a499-11e9-8a9c-6fe3d6c40246.png)

**Comment by dodumosu** [comment]
does the Telerivet API client have the "send message" permission turned on?
![Add_API_Client_-__Private_Browsing_](https://user-images.githubusercontent.com/1408662/61142097-dd03bb80-a4c6-11e9-872d-1ada8d3aea21.png)

**Comment by blynchNDI** [comment]
Ok, yeah I was wondering if they were disconnected or somehow different. It is turned on for both viewing and sending messages:

![Screenshot from 2019-07-12 12-27-12](https://user-images.githubusercontent.com/31080607/61143540-81bed280-a4a0-11e9-9ac0-bc2573f1bd65.png)

**Comment by blynchNDI** [comment]
(I made a copy of my settings.ini file for the apolloqa site, so if it's easier or you can't recreate on your end, feel free to edit anything on there or try setting it up for yourself with a telerivet connection)

**Comment by blynchNDI** [comment]
Here's the error from the docker error logs when sending from the checklist screen:

```
[2019-07-12 17:23:30,724] ERROR in app: Exception on /submissions/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/apollo/frontend/__init__.py", line 10, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/app/apollo/submissions/views_submissions.py", line 284, in submission_list
    models.Submission.participant).select_related(1)
AttributeError: 'BaseQuery' object has no attribute 'select_related'
```

**Comment by blynchNDI** [comment]
Message blasts are working from both the checklist and participant page
